name: Continuous Integration and Deployment Workflow

on:
  push:
    branches:
      - main
      
env:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY: ${{ secrets.KEY }}
  PASSPHRASE: ${{ secrets.PASSPHRASE }}
  
jobs:
  build-and-deploy:
    
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with: 
        node-version: '14.x'
      
    - name: Install dependencies for backend
      run: |
        cd app/backend
        npm ci
        
    - name: Test backend
      run: |
        cd app/backend
        npm test
        
    - name: Deploy using ssh
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        args: "-o StrictHostKeyChecking=no"
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: '22'
        local_dir: app/
        remote_dir: /var/www/
